components:
  schemas:
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    RegisterRequestBody:
      additionalProperties: false
      dependentRequired:
        email:
          - password
        phone_number:
          - phone_number_country_code_id
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/RegisterRequestBody.json
          format: uri
          readOnly: true
          type: string
        email:
          format: email
          type:
            - string
            - "null"
        first_name:
          minLength: 1
          type:
            - string
            - "null"
        last_name:
          minLength: 1
          type:
            - string
            - "null"
        password:
          minLength: 8
          type:
            - string
            - "null"
        phone_number:
          format: phone
          minLength: 10
          type:
            - string
            - "null"
        phone_number_country_code_id:
          format: uuid
          type:
            - string
            - "null"
      type: object
    RegisterResponseData:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/RegisterResponseData.json
          format: uri
          readOnly: true
          type: string
        data:
          $ref: "#/components/schemas/User"
      type: object
    User:
      additionalProperties: false
      properties:
        created_at:
          examples:
            - "2019-08-24T14:15:22Z"
          format: date-time
          type: string
        email:
          format: email
          type:
            - string
            - "null"
        first_name:
          type:
            - string
            - "null"
        id:
          format: uuid
          type: string
        last_name:
          type:
            - string
            - "null"
        phone_number:
          type:
            - string
            - "null"
        phone_number_country_code:
          type:
            - string
            - "null"
      required:
        - id
        - first_name
        - last_name
        - email
        - phone_number
        - phone_number_country_code
        - created_at
      type: object
info:
  title: API First Service
  version: 1.0.0
openapi: 3.1.0
paths:
  /v1/users/register:
    post:
      description: |

        This endpoint allows users to register for the platform. Users can register using one of the following methods:
        - **Email and Password**: Users provide their email and password to create an account.
        - **Phone Number**: Users provide their phone number to register.

        Additionally, users can optionally provide their first name and last name during registration.


        **Note**: Either email and password or phone must be provided; providing both is optional but not required.
        If both email and phone number are provided, the account will be created using the email.
      operationId: user_register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequestBody"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponseData"
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
      summary: Register an user
      tags:
        - USERS
